### ISSUE TITLE
Crossing not considered

### ISSUE THREAD

**Issue by HiroKoni** [hiro2620/tg-wating-time-analyzer#1]
**Description**
Keisei Makuhari sta. has a crossing in it, which forces passengers getting off the train to wait trains to go.
However, main.py doesn't consider it.
This may cause serious effect on students' arrival time at the gateway.

**Comment by hiro2620** [comment]
As this program is designed to determine the time to walk only by mean value and standard deviation, I think the large refactoring is needed to consider things that happen on the way to school. 
I agree with you, but I'm not planning to take it for now.
Modifying STATIONS_CONFIG or TRAINS_CONFIG to emulate waiting time of crossing might be an alternative.

Thanks, anyway.

**Comment by HiroKoni** [comment]
The biggest problem is, that while some of the students using Keisei can pass
